### PR TITLE
Update main.lua for battery widget

### PR DESCRIPTION
**Pull request by lshems**
removed all global variables to allow multiple instances of this widget and prevent unwanted interaction with other widgets.

only shadowed as widget context local variable remains. don't think that is a problem, as it is not changed in the widget, but please check.

I didn't test the new script. only did manual corrections. i might have overseen something.

### CODE REVIEW

**Comment by offer-shmuely** [comment]
thanks a lot
now i understand LUA better!
however, you did the changes on old code, I already changed it with many new global parameters :-( (to improve performance)
on branch: 
https://github.com/offer-shmuely/opentx/tree/horus_widget_batt_check_updates

I will update the code per you guidelines, and ask for review

**Comment by offer-shmuely** [comment]
can you check the new code at:
https://github.com/offer-shmuely/opentx/blob/horus_widget_batt_check_updates/radio/sdcard/horus/WIDGETS/BattCheck/main.lua

**Comment by lshems** [comment]
All seems fine at first glance. I will write a widget to show 'forgotten' global variables.

Just the range in the color setter function.

It is checked for being zero before it exists.

After the function is run, it doesn't exist anymore until next call.

Check my original proposal for that part.

**Comment by offer-shmuely** [comment]
fixed as well
thanks!

**Comment by lshems** [comment]
No thanks. You're welcome.

P.s. your struggle about the widget zones sizes is difficult. Don't put to much effort in it.

Perhaps making a widget setting explicitly allowing out of zone usage with an exclamation mark will get it approved by the opentx guys.

If not, you can always keep your own versions available in your own fork.

Check repository.justfly.solutions if you need a place to host them. Github can be scary to lots of people.

**Comment by offer-shmuely** [comment]
closing since all the suugestion merged (manuall/y)

**Pull request closed without merging**
